extends Resource

const WEAPONS = [
    {
        "id": "pistol",
        "name": "Pistol",
        "damage": 15.0,
        "fire_rate": 3.0,
        "projectile_speed": 55.0,
        "spread": 0.01,
        "automatic": false,
        "projectile_scale": 0.2,
        "projectile_color": Color(1.0, 0.86, 0.56),
        "pickup_color": Color(1.0, 0.88, 0.54),
        "fire_style": "pistol",
    },
    {
        "id": "rifle",
        "name": "Pulse Rifle",
        "damage": 10.0,
        "fire_rate": 8.0,
        "projectile_speed": 75.0,
        "spread": 0.02,
        "automatic": true,
        "projectile_scale": 0.18,
        "projectile_color": Color(0.64, 0.92, 1.0),
        "pickup_color": Color(0.58, 0.86, 1.0),
        "fire_style": "burst",
    },
    {
        "id": "shotgun",
        "name": "Scattergun",
        "damage": 8.0,
        "fire_rate": 1.2,
        "projectile_speed": 50.0,
        "spread": 0.08,
        "pellets": 6,
        "automatic": false,
        "projectile_scale": 0.25,
        "projectile_color": Color(1.0, 0.7, 0.48),
        "pickup_color": Color(0.95, 0.64, 0.46),
        "fire_style": "kick",
    },
    {
        "id": "rocket",
        "name": "Rocket Launcher",
        "damage": 40.0,
        "fire_rate": 0.8,
        "projectile_speed": 35.0,
        "spread": 0.03,
        "automatic": false,
        "projectile_scale": 0.3,
        "explosive": true,
        "projectile_color": Color(1.0, 0.46, 0.34),
        "pickup_color": Color(1.0, 0.54, 0.32),
        "fire_style": "heavy",
    },
    {
        "id": "laser",
        "name": "Laser Beam",
        "damage": 6.0,
        "fire_rate": 14.0,
        "projectile_speed": 120.0,
        "spread": 0.0,
        "automatic": true,
        "projectile_scale": 0.12,
        "projectile_color": Color(0.64, 1.0, 0.7),
        "pickup_color": Color(0.5, 1.0, 0.72),
        "fire_style": "beam",
    }
]
